name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: 17
        distribution: temurin

    - uses: actions/checkout@v3

    - name: Restore Build Cache
      uses: actions/cache@v4.0.2
      with:
        path: ~/.m2/repository
        key: v1-flyway-${{ hashFiles('project.clj') }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test

    - name: check clojure code format
      run: lein cljfmt check

    - name: check deprecated dependency version
      run: lein ancient
